name: Tests

on:
  push:
    branches:
      - master
      - v*
  pull_request:
    branches:
    - master
    - v*

jobs:
  build:
    strategy:
      matrix:
        go-version: ["1.15", "1.19", "1.20"]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@4ab57d7ea2fd0c9948210b2e0784e280674e7144
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@b80ff79f1755d06ba70441c368a6fe801f5f3a62
    - name: Run static checks
      uses: golangci/golangci-lint-action@608f9e14ec67b08f62730e670e43fbb72cabe879
      with:
        version: v1.51.1
        # use our .golangci.yml and configure output to be logged in the GHA, in addition to annotating the commit.
        # see https://github.com/golangci/golangci-lint-action/issues/119#issuecomment-981090648 for output
        args: --config=.golangci.yml --verbose --out-${NO_FUTURE}format colored-line-number --timeout 5m
        skip-cache: true
    - name: Build
      run: go build
    - name: Run unit tests
      run: go test -v -race -cover
